# Generated by Django 3.0.4 on 2020-04-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200426_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
    ]
